# Generated by Django 5.1.5 on 2025-02-02 05:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Average rating of the movie based on user reviews (0 indicates no ratings).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have marked this movie as a favorite.', related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate the movie from 1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('review', models.TextField(help_text='Write your review here (maximum 1000 characters).', max_length=1000, verbose_name='Review')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movie Review',
                'verbose_name_plural': 'movie Reviews',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['movie'], name='movie_movie_movie_i_97ee40_idx'), models.Index(fields=['user'], name='movie_movie_user_id_afcca4_idx'), models.Index(fields=['rating'], name='movie_movie_rating_dac2bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('movie', 'user'), name='unique_user_movie_review')],
            },
        ),
    ]
